language: node_js
node_js: stable

cache:
  directories:
    - node_modules

git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - cd src/stylesheet/
  - npm install
  - npm run build
  - cd ../..

install:
  - npm install

script:
  - npm run dist

after_script:
  - cd dist
  - git init
  - git config user.name "koppthe"
  - git config user.email "koppthe@gmail.com"
  - git add .
  - git commit -m "Update Document"
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:gh-pages

branches:
  only:
    - master

env:
  global:
    - GH_REF: github.com/at-ui/at-ui.git
